[theme]
primaryColor = "#2E86C1"  # Deep blue accent
backgroundColor = "#000000"  # Pure black background
secondaryBackgroundColor = "#1A1A2E"  # Dark navy for contrast
textColor = "#FFFFFF"  # White text
font = "sans serif"